version: '3.8'
services:
  db:
    image: postgres:15
    container_name: nextjs-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: canada_citizenship
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: nextjs-postgres-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  postgres_data:
